### ISSUE TITLE
Support jumps to dynamically computed labels?

### ISSUE THREAD

**Issue by magicgoose** [snoack/python-goto#14]
Example:

	from goto import with_goto

	@with_goto
	def example():
	    label_number = 1
	    getattr(goto, f'l_{label_number}')
	    label.l_0
	    print(0)
	    label.l_1
	    print(1)

	example()

AFAIK this code "does" the same as if I replaced the line with getattr with simply `goto.l_1`. But currently it doesn't work:

	Traceback (most recent call last):
	  File "example.py", line 12, in <module>
	    example()
	  File "example.py", line 6, in example
	    getattr(goto, f'l_{label_number}')
	NameError: name 'goto' is not defined

Tested with CPython 3.6.4 and PyPy3 5.9.0-beta0

**Comment by snoack** [comment]
That `label .foo` is technical parsed as attribute lookup is an implementation detail, and since `getattr(label, 'foo')` results into different bytecode (it's a function call not an attribute lookup on the bytecode-level), it is ignored when the `@with_goto` decorator rewrites the bytecode. Furthermore, in order to support calculated jump target, we'd have to keep a mapping of names and their destination, and resolve them at runtime. This is not supported at the moment, and might be impossible with the current approach, also considering that the code to perform the jump (with the current approach) can not be any larger than the original bytecode it replaces. However, one workaround would be, generating a string of Python code and using `exec()` after resolving all labels.

**Comment by ioistired** [comment]
this could be done by intercepting `goto *'x'`, the bytecode for which should have similar complexity to attribute lookups.
